# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet workload install android && dotnet workload install ios wasm-tools-net9 && dotnet workload restore && dotnet workload update && dotnet workload install wasm-tools && dotnet nuget locals all --clear && dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      # 发布项目，生成独立且单一的exe文件
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-exe
        path: ./publish/*.exe # 上传生成的exe文件
